version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    links:
      - postgres
    container_name: user-api

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "user_db"
    container_name: postgres-user-api