version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-mysql:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      - DB_SERVER=mysql
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  db-mysql:
