version: '3'
services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/data/db

  app:    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      - DB_SERVER=mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

volumes:
  db: